apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: traefik-dashboard-auth
  namespace: traefik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: traefik-dashboard-auth
    creationPolicy: Owner
  data:
    - secretKey: users
      remoteRef:
        key: traefik/users
