apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homelab-repo
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: homelab-repo
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
  data:
    - secretKey: type
      remoteRef:
        key: argocd-repo/type
    - secretKey: url
      remoteRef:
        key: argocd-repo/repo-url
    - secretKey: username
      remoteRef:
        key: argocd-repo/username
    - secretKey: password
      remoteRef:
        key: argocd-repo/password
