apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homelab-repo
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: homelab-repo
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
  data:
    - secretKey: type
      remoteRef:
        key: homelab/argocd/homelab-repo
        property: type
    - secretKey: url
      remoteRef:
        key: homelab/argocd/homelab-repo
        property: url
    - secretKey: username
      remoteRef:
        key: homelab/argocd/homelab-repo
        property: username
    - secretKey: password
      remoteRef:
        key: homelab/argocd/homelab-repo
        property: password
